"""rename department

Revision ID: 505dca9dbae3
Revises: 9107f9089b2d
Create Date: 2024-08-25 21:13:32.873606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '505dca9dbae3'
down_revision = '9107f9089b2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
