"""rename address

Revision ID: 92acf4f3961c
Revises: 505dca9dbae3
Create Date: 2024-08-25 21:18:40.738307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92acf4f3961c'
down_revision = '505dca9dbae3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
